spring.application.name=AI-Agent-Chatbot

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o